import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, renameSync, rmSync, statSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import type { Page } from "@playwright/test";

/**
 * Workspaces generated by scripts/bench/seed-workspace.ts (synthetic data
 * only), written straight into IndexedDB the way a migration leaves them.
 */
export interface SeedPage {
  pageId: string;
  title: string;
  strokes: number;
  sectionId: string;
  sectionTitle: string;
  token: string;
}

const repoRoot = join(import.meta.dirname, "..", "..");

const LOCK_STALE_MS = 10 * 60_000;

function sleepSync(ms: number): void {
  Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, ms);
}

/** Runs `action` while holding a directory lock shared by every worker process. */
function withLock<T>(lockDir: string, action: () => T): T {
  for (;;) {
    try {
      mkdirSync(lockDir);
      break;
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== "EEXIST") throw error;
      // A worker that was killed while generating leaves its lock behind.
      try {
        if (Date.now() - statSync(lockDir).mtimeMs > LOCK_STALE_MS) rmSync(lockDir, { recursive: true, force: true });
      } catch {
        // The holder released it in the meantime.
      }
      sleepSync(200);
    }
  }
  try {
    return action();
  } finally {
    rmSync(lockDir, { recursive: true, force: true });
  }
}

/**
 * Builds the seed generator and writes a seed for `args`, returning the
 * directory that holds it. The directory name carries a hash of the generator
 * and the arguments, so a seed is never replaced or read half-written, and
 * checkouts with different generators can share `baseDir`: a seed made by an
 * older generator would fail the app's document validation at startup.
 * Generating a page with thousands of strokes takes seconds.
 *
 * Playwright runs each worker's `beforeAll` at the same time, so this is safe
 * to call from several processes: a lock serializes the build of the generator
 * (which shares one output directory) and the seed is written beside its final
 * directory and renamed into place.
 */
export function generateSeed(baseDir: string, args: readonly string[]): string {
  return withLock(`${baseDir}.lock`, () => {
    // Inside the repository, so the bundle resolves Automerge from node_modules.
    const buildDir = join(repoRoot, "node_modules", ".cache", "canvink-e2e-seed");
    execFileSync("pnpm", ["exec", "vite", "build", "--config", "scripts/bench/vite.seed.config.mjs"], {
      cwd: repoRoot,
      env: { ...process.env, CANVINK_BENCH_BUILD: buildDir },
      stdio: "pipe",
    });
    const bundle = join(buildDir, "seed-workspace.js");
    const key = createHash("sha256").update(readFileSync(bundle)).update(args.join("\0")).digest("hex").slice(0, 16);
    const seedDir = `${baseDir}-${key}`;
    if (existsSync(join(seedDir, "seed.json"))) return seedDir;
    const stagingDir = `${seedDir}.staging`;
    rmSync(stagingDir, { recursive: true, force: true });
    execFileSync("node", [bundle, "--out", stagingDir, ...args], { cwd: repoRoot, stdio: "pipe" });
    renameSync(stagingDir, seedDir);
    return seedDir;
  });
}

/** Writes the seed's records into this origin's IndexedDB; returns its pages. */
export async function seedWorkspace(page: Page, seedDir: string): Promise<SeedPage[]> {
  const seedJson = await readFile(join(seedDir, "seed.json"));
  const seedBin = await readFile(join(seedDir, "seed.bin"));
  await page.route("**/__seed/seed.json", (route) => route.fulfill({ body: seedJson, contentType: "application/json" }));
  await page.route("**/__seed/seed.bin", (route) => route.fulfill({ body: seedBin, contentType: "application/octet-stream" }));
  await page.route("**/__seed/blank", (route) => route.fulfill({ body: "<!doctype html><title>seed</title>", contentType: "text/html" }));
  await page.goto("/__seed/blank");
  return page.evaluate(async () => {
    const seed = await (await fetch("/__seed/seed.json")).json();
    const binary = new Uint8Array(await (await fetch("/__seed/seed.bin")).arrayBuffer());
    const database = await new Promise<IDBDatabase>((resolve, reject) => {
      const request = indexedDB.open(seed.database, 1);
      request.onupgradeneeded = () => request.result.createObjectStore(seed.store);
      request.onsuccess = () => resolve(request.result);
      request.onerror = () => reject(request.error);
    });
    const bytes = (record: { offset: number; length: number }) => binary.slice(record.offset, record.offset + record.length);
    for (let start = 0; start < seed.records.length; start += 200) {
      await new Promise<void>((resolve, reject) => {
        const transaction = database.transaction(seed.store, "readwrite");
        const store = transaction.objectStore(seed.store);
        for (const record of seed.records.slice(start, start + 200)) {
          if (record.type === "segment") continue;
          if (record.type === "json") store.put(record.value, record.key);
          else if (record.type === "bytes") store.put(bytes(record), record.key);
          else if (record.type === "asset") store.put({ ...record.value, bytes: bytes(record) }, record.key);
          else store.put({ key: record.chunkKey, bytes: bytes(record) }, record.key);
        }
        transaction.oncomplete = () => resolve();
        transaction.onerror = () => reject(transaction.error);
      });
    }
    database.close();
    // Ink segments (seeds made with the default `--ink segments`) live in their own database.
    const segments = seed.records.filter((record: { type: string }) => record.type === "segment");
    if (segments.length > 0) {
      const inkDatabase = await new Promise<IDBDatabase>((resolve, reject) => {
        const request = indexedDB.open("canvink-ink-segments", 1);
        request.onupgradeneeded = () => request.result.createObjectStore("segments");
        request.onsuccess = () => resolve(request.result);
        request.onerror = () => reject(request.error);
      });
      for (let start = 0; start < segments.length; start += 100) {
        await new Promise<void>((resolve, reject) => {
          const transaction = inkDatabase.transaction("segments", "readwrite");
          const store = transaction.objectStore("segments");
          for (const record of segments.slice(start, start + 100)) store.put(bytes(record), `blob:${record.key}`);
          transaction.oncomplete = () => resolve();
          transaction.onerror = () => reject(transaction.error);
        });
      }
      inkDatabase.close();
    }
    return seed.pages;
  });
}

/**
 * Number of strokes the canvas of the shown page has painted; 0 while a page
 * is still loading (the previous page's canvas stays mounted meanwhile).
 */
export async function shownStrokeCount(page: Page): Promise<number> {
  return page.evaluate(() => {
    if (document.querySelector("[data-page-loading]")) return 0;
    return Number(document.querySelector("[data-ink-stroke-count]")?.getAttribute("data-ink-stroke-count") ?? 0);
  });
}

/** Deletes the persisted search index, as a fresh import or "rebuild corrupt projection" does. */
export async function deleteSearchDatabases(page: Page): Promise<void> {
  // What a fresh import or "rebuild corrupt projection" leaves behind: no
  // persisted records and no cached PDF or OCR text.
  await page.evaluate(async () => {
    for (const name of ["canvink-search-v3", "canvink-search-derived-v1"]) {
      await new Promise<void>((resolve) => {
        const request = indexedDB.deleteDatabase(name);
        request.onsuccess = request.onerror = request.onblocked = () => resolve();
      });
    }
  });
}
